version: '3'
services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
    links:
     - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/rocket
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
  mongo:
    image: mongo:4.0
    volumes:
    - ./data/db:/data/db
    - ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.enable=false"
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/mongodb
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs

  mongo-init-replica:
    image: mongo:4.0
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    links:
     - mongo
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/mongodb-init-replica
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs